### ISSUE TITLE
Hast du bock die LernSax App API zu integrieren?

### ISSUE THREAD

**Issue by TKFRvisionOfficial** [niggo-edw/LernsaxBot#1]
Frage an dich. Ich bin gerade ultra im Prüfungstress und habe sonst keine Zeit für gar nix. Aber vor einigen Monaten habe ich erfolgreich die API die zur Kommunikations mit der App verwendet wird reverse engineered. Ich habe dann einen WhatsApp Bot geschrieben der mir Automatisch die Aufgaben per WhatsApp weiterleitet. Da ich direkt an die API rangehe ist alles viel schneller.

LernSax nutzt json-rpc und ein nonce login system auf einem sogennanten WebWeaver System. Du schickst meistens eine Liste an befehlen. Ich habe unteraderem eine Modifizierte APK der App erstellt in die über den Android Debugger jegliche Request raushaut so das man die Kommunikations einfach mitlesen kann. Die API umfasst vielmehr als in der App integriert deswegen muss man leider oft raten.

Dennoch kann ich dir mal schicken was ich so gemacht habe damit das mal jemand in eine schöne nice Pythonform stecken kann.

Also schreib mir mal...

**Comment by wenik35** [comment]
Hi, klingt verdammt spannend. Schick mir den Spaß gern mal rüber, da lassen sich bestimmt einige interessante Sachen mit anstellen. Falls du das aus der Github-Issues-Section rausverlagern willst, schreib mir mal ne Mail an wunderwitz@gmx.net, konnte bei dir auf dem Profil leider keine finden

**Comment by TKFRvisionOfficial** [comment]
Hast ja geantwortet...
